### ISSUE TITLE
Add Toggles

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-dev-tools#1]
Just a toggle to turn taxes on and off from the toolbar.

**Comment by pippinsplugins** [comment]
Oh yes please

**Comment by cklosowski** [comment]
:+1:

**Comment by cklosowski** [comment]
Updated the title to reflect what I'm going to do, taking inspiration from the Plugin Toggle plugin, I'll have a way to toggle the on/off settings in EDD
